repos:
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    - id: isort
      exclude: ^.*\b(migrations)\b.*$

-   repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
    - id: black
      exclude: ^.*\b(migrations)\b.*$
      args: [ --config, pyproject.toml ]

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      exclude: ^.*\b(migrations)\b.*$
      args: [--config, setup.cfg]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
        exclude: ^.*\b(migrations)\b.*$
        args: [--config, setup.cfg]