version: "3.4"
services:

  app:
    container_name: ${APP_CONTAINER_NAME}
    restart: always
    build:
      context: .
      args:
        - ENV=${ENV}
    env_file:
      - .env
    volumes:
      - .:/src
    command: bash -c "python src/manage.py runserver 0.0.0.0:8000"
    ports:
      - ${PORT_APP}:8000
    depends_on:
      - db

  db:
    image: postgres:12
    container_name: ${DB_CONTAINER_NAME}
    env_file: .env
    volumes:
      - ./docker/postgres_data:${PGDATA}
    ports:
      - ${LOCAL_PORT_DB}:${POSTGRES_PORT}
