# Generated by Django 4.1.2 on 2022-10-11 14:18

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.CreateModel(
            name='EnterpriseNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Сеть предприятий',
                'verbose_name_plural': 'Сети предприятий',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('description', models.CharField(max_length=1024, verbose_name='Описание')),
                ('districts', models.ManyToManyField(related_name='institutions', to='institutions.district', verbose_name='Районы')),
                ('enterprise_network', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions', to='institutions.enterprisenetwork', verbose_name='Сеть предприятий')),
            ],
            options={
                'verbose_name': 'Предприятие',
                'verbose_name_plural': 'Предприятия',
            },
        ),
        migrations.CreateModel(
            name='ProductInstitutionAssociated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution', verbose_name='Предприятие')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар/услуга')),
            ],
            options={
                'verbose_name': 'Связь товара/услуги и предприятия',
                'verbose_name_plural': 'Связи товара/услуги и предприятия',
            },
        ),
        migrations.AddField(
            model_name='institution',
            name='products',
            field=models.ManyToManyField(related_name='institutions', through='institutions.ProductInstitutionAssociated', to='products.product', verbose_name='Товары и услуги'),
        ),
        migrations.AddConstraint(
            model_name='productinstitutionassociated',
            constraint=models.UniqueConstraint(fields=('institution', 'product'), name='institution_and_product_unique'),
        ),
    ]
